export const LOGIN_VENDOR_REQUEST = "LOGIN_VENDOR_REQUEST";
export const LOGIN_VENDOR_SUCCESS = "LOGIN_VENDOR_SUCCESS";
export const LOGIN_VENDOR_FAIL = "LOGIN_VENDOR_FAIL";

export const REGISTER_VENDOR_REQUEST = "REGISTER_VENDOR_REQUEST";
export const REGISTER_VENDOR_SUCCESS = "REGISTER_VENDOR_SUCCESS";
export const REGISTER_VENDOR_FAIL = "REGISTER_VENDOR_FAIL";

export const LOAD_VENDOR_REQUEST = "LOAD_VENDOR_REQUEST";
export const LOAD_VENDOR_SUCCESS = "LOAD_VENDOR_SUCCESS";
export const LOAD_VENDOR_FAIL = "LOAD_VENDOR_FAIL";

export const LOGOUT_VENDOR_SUCCESS = "LOGOUT_VENDOR_SUCCESS";
export const LOGOUT_VENDOR_FAIL = "LOGOUT_VENDOR_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
