export const LOGIN_VENDOR_REQUEST = "LOGIN_VENDOR_REQUEST";
export const LOGIN_VENDOR_SUCCESS = "LOGIN_VENDOR_SUCCESS";
export const LOGIN_VENDOR_FAIL = "LOGIN_VENDOR_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
